# 03-database-redis.yaml
# Database and Redis Services

# PostgreSQL Database - Worker Node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-database
  namespace: face-recognition-system
  labels:
    app: postgresql
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        component: database
    spec:
      nodeSelector:
        kubernetes.io/hostname: bluedovve-ms-7b98  # Worker node
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_USER
        resources:
          limits:
            cpu: "2000m"
            memory: "4Gi"
          requests:
            cpu: "1000m"
            memory: "2Gi"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
          initialDelaySeconds: 45
          periodSeconds: 10
      volumes:
      - name: postgres-data
        emptyDir: {}  # Use persistent volume in production

---
# Redis Primary - Worker Node (with password and optimized config)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-primary
  namespace: face-recognition-system
  labels:
    app: redis-primary
    component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-primary
  template:
    metadata:
      labels:
        app: redis-primary
        component: cache
    spec:
      nodeSelector:
        kubernetes.io/hostname: bluedovve-ms-7b98  # Worker node
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        command:
        - redis-server
        - --requirepass
        - admin
        - --protected-mode
        - "no"
        - --maxmemory
        - 512mb
        - --maxmemory-policy
        - allkeys-lru
        - --save
        - "900 1"
        - --save
        - "300 10"
        - --save
        - "60 10000"
        - --appendonly
        - "no"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - admin
            - ping
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -a
            - admin
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10

---
# Redis Channels - Worker Node (port 6380 with password)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-channels
  namespace: face-recognition-system
  labels:
    app: redis-channels
    component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-channels
  template:
    metadata:
      labels:
        app: redis-channels
        component: cache
    spec:
      nodeSelector:
        kubernetes.io/hostname: bluedovve-ms-7b98  # Worker node
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6380
        command:
        - redis-server
        - --port
        - "6380"
        - --requirepass
        - admin
        - --protected-mode
        - "no"
        - --maxmemory
        - 512mb
        - --maxmemory-policy
        - allkeys-lru
        - --save
        - "900 1"
        - --save
        - "300 10"
        - --save
        - "60 10000"
        - --appendonly
        - "no"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -p
            - "6380"
            - -a
            - admin
            - ping
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -p
            - "6380"
            - -a
            - admin
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10